# Metadata Schema for Software Tools and Libraries
# Organized by logical sections for better maintainability

# Core identification and overview
basic_info:
  - tool_name
  - overview_description
  - key_features
  - use_cases
  - supported_platforms

# Technical specifications
technical_specs:
  - dependencies
  - system_requirements
  - performance_considerations
  - supported_languages
  - supported_file_formats

# Installation and setup
setup_info:
  - installation_setup
  - configuration_guide
  - quick_start_tutorial

# Documentation and learning resources
documentation:
  - official_documentation
  - tutorials_examples
  - community_tutorials
  - api_reference

# Community and support
community:
  - community_support
  - forums_channels
  - ecosystem_packages

# Licensing and versioning
legal_versioning:
  - licensing
  - latest_version
  - release_date
  - version_history

# External references and links
references:
  - official_website
  - github_repository
  - documentation_links
  - additional_resources

# Category-specific fields organized by domain
category_fields:
  "AI/ML Development Tools":
    - model_types_supported
    - training_capabilities
    - inference_features
    - hardware_acceleration
    - ml_framework_integration
    - model_deployment_options
    - example_notebooks

  "Data Science and Analytics Tools":
    - data_formats_supported
    - visualization_capabilities
    - statistical_analysis
    - data_processing_features
    - ml_library_integration
    - data_export_formats
    - interactive_features

  "Creative and Media Tools":
    - media_formats_supported
    - rendering_capabilities
    - plugin_ecosystem
    - user_interface
    - collaboration_features
    - export_formats
    - performance_optimization

  "Developer Tools":
    - language_support
    - ide_integration
    - version_control_integration
    - debugging_tools
    - code_analysis
    - build_deployment
    - extension_ecosystem

  "Large Language Models (LLM) Tools":
    - supported_model_types
    - prompt_engineering_tools
    - fine_tuning_capabilities
    - api_sdk_availability
    - model_management
    - deployment_options
    - integration_frameworks

# Field descriptions for validation and documentation
field_descriptions:
  # Basic Info
  tool_name: "Name of the tool/library/framework"
  overview_description: "Brief description of what the tool does and its purpose"
  key_features: "Main capabilities and features of the tool"
  use_cases: "Primary applications and use cases"
  supported_platforms: "Operating systems and platforms supported"
  
  # Technical Specs
  dependencies: "Required dependencies, libraries, or tools needed"
  system_requirements: "Hardware and software requirements"
  performance_considerations: "Performance characteristics and optimization notes"
  supported_languages: "Programming languages and technologies supported"
  supported_file_formats: "Input and output file formats supported"
  
  # Setup Info
  installation_setup: "How to install and configure the tool"
  configuration_guide: "Detailed configuration instructions"
  quick_start_tutorial: "Quick start guide for beginners"
  
  # Documentation
  official_documentation: "Official documentation and guides"
  tutorials_examples: "Tutorials and example projects"
  community_tutorials: "Community-created tutorials and resources"
  api_reference: "API documentation and reference"
  
  # Community
  community_support: "Community size and support channels"
  forums_channels: "Forums, Discord, Slack channels"
  ecosystem_packages: "Related packages and ecosystem"
  
  # Legal/Versioning
  licensing: "License type and terms"
  latest_version: "Current version information"
  release_date: "Latest release date"
  version_history: "Version history and changelog"
  
  # References
  official_website: "Official website URL"
  github_repository: "GitHub repository link"
  documentation_links: "Additional documentation links"
  additional_resources: "Other relevant resources"
  
  # AI/ML specific
  model_types_supported: "Types of models that can be used"
  training_capabilities: "Training features and capabilities"
  inference_features: "Inference and prediction features"
  hardware_acceleration: "GPU/TPU support and optimization"
  ml_framework_integration: "Integration with ML frameworks"
  model_deployment_options: "Deployment and hosting options"
  example_notebooks: "Sample Jupyter notebooks and projects"
  
  # Data Science specific
  data_formats_supported: "File formats and data types supported"
  visualization_capabilities: "Charting and visualization features"
  statistical_analysis: "Statistical analysis capabilities"
  data_processing_features: "Data processing and manipulation"
  ml_library_integration: "Machine learning library integration"
  data_export_formats: "Export and output formats"
  interactive_features: "Interactive features and widgets"
  
  # Creative/Media specific
  media_formats_supported: "Media file formats supported"
  rendering_capabilities: "Rendering engine and performance"
  plugin_ecosystem: "Available plugins and extensions"
  user_interface: "UI/UX description and workflow"
  collaboration_features: "Team collaboration and sharing"
  export_formats: "Output and export formats"
  performance_optimization: "Performance optimization features"
  
  # Developer Tools specific
  language_support: "Programming languages supported"
  ide_integration: "IDE and editor integration"
  version_control_integration: "Git and version control integration"
  debugging_tools: "Debugging tools and capabilities"
  code_analysis: "Code analysis and linting features"
  build_deployment: "CI/CD and deployment integration"
  extension_ecosystem: "Available extensions and plugins"
  
  # LLM Tools specific
  supported_model_types: "Types of language models supported"
  prompt_engineering_tools: "Prompt engineering and optimization"
  fine_tuning_capabilities: "Model fine-tuning and customization"
  api_sdk_availability: "API and SDK availability"
  model_management: "Model versioning and management"
  deployment_options: "Deployment and hosting options"
  integration_frameworks: "Integration with other LLM tools"

# Validation rules for field types
field_types:
  # Basic Info
  tool_name: "string"
  overview_description: "text"
  key_features: "list"
  use_cases: "list"
  supported_platforms: "list"
  
  # Technical Specs
  dependencies: "list"
  system_requirements: "text"
  performance_considerations: "text"
  supported_languages: "list"
  supported_file_formats: "list"
  
  # Setup Info
  installation_setup: "text"
  configuration_guide: "text"
  quick_start_tutorial: "text"
  
  # Documentation
  official_documentation: "list"
  tutorials_examples: "list"
  community_tutorials: "list"
  api_reference: "list"
  
  # Community
  community_support: "text"
  forums_channels: "list"
  ecosystem_packages: "list"
  
  # Legal/Versioning
  licensing: "string"
  latest_version: "string"
  release_date: "string"
  version_history: "text"
  
  # References
  official_website: "string"
  github_repository: "string"
  documentation_links: "list"
  additional_resources: "list"
  
  # Category-specific fields
  model_types_supported: "list"
  training_capabilities: "text"
  inference_features: "text"
  hardware_acceleration: "text"
  ml_framework_integration: "text"
  model_deployment_options: "text"
  example_notebooks: "list"
  data_formats_supported: "list"
  visualization_capabilities: "text"
  statistical_analysis: "text"
  data_processing_features: "text"
  ml_library_integration: "text"
  data_export_formats: "list"
  interactive_features: "text"
  media_formats_supported: "list"
  rendering_capabilities: "text"
  plugin_ecosystem: "text"
  user_interface: "text"
  collaboration_features: "text"
  export_formats: "list"
  performance_optimization: "text"
  language_support: "list"
  ide_integration: "text"
  version_control_integration: "text"
  debugging_tools: "text"
  code_analysis: "text"
  build_deployment: "text"
  extension_ecosystem: "text"
  supported_model_types: "list"
  prompt_engineering_tools: "text"
  fine_tuning_capabilities: "text"
  api_sdk_availability: "text"
  model_management: "text"
  deployment_options: "text"
  integration_frameworks: "text" 